### ISSUE TITLE
Compatability suggestion

### ISSUE THREAD

**Issue by NixityNull** [SR2610/Creeper-Confetti-Forge-Edition#2]
Is there any chance you could make this compatable with the googlyeyes mod (https://www.curseforge.com/minecraft/mc-mods/googlyeyes) so that only creepers  with googly eyes explode into confetti? It would make a subtle tell to which ones are duds.

**Comment by SR2610** [comment]
Not implementing this as their isn't any easy approach as the googly eyes are applied randomly so it would be a lot of effort to add an enhanced compatibility feature and would add unnecessary complexity to the mod.
